ブログページの追加（git & github勉強会）
AizuGeekDojo/AizuGeekDojo.github.io pull request #102
Opened 2021-07-26 01:53 UTC by wancom

## 変更内容

Git & GitHub勉強会のブログ記事を追加しました。

## 関連するページ

/blog/2021-07-22/Git%20&%20GitHub勉強会を行いました

2021-07-26 02:25 UTC, Mono-4 approved these changes
LGTM

2021-07-26 02:39 UTC, KATO-Eriko commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +今年もAizu Geek Dojoに新しくSAが入ってきましたが、SAの技術力向上とSA業務の効率化を目指し、今回SA向けにGitとGitHubの使い方を教える勉強会を行いました。
「自分が講師となり」という一文を加えてはいかがでしょう。大変だったことの箇所で記事作成者がスライドを作ったことが分かるのですが、冒頭のところで分かるようにした方がいいと思います。

2021-07-26 02:48 UTC, KATO-Eriko reviewed
スライドは公開しても大丈夫であれば、GitHubのURLを付けてはどうでしょうか。

2021-07-26 04:24 UTC, wancom commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +今年もAizu Geek Dojoに新しくSAが入ってきましたが、SAの技術力向上とSA業務の効率化を目指し、今回SA向けにGitとGitHubの使い方を教える勉強会を行いました。
レビューありがとうございます。
こんな感じで修正してみたいと思います。
```suggestion
今年もAizu Geek Dojoに新しくSAが入ってきましたが、SAの技術力向上とSA業務の効率化を目指し、今回SA向けに自分が講師となってGitとGitHubの使い方を教える勉強会を行いました。
```

2021-07-26 04:25 UTC, wancom commented
> スライドは公開しても大丈夫であれば、GitHubのURLを付けてはどうでしょうか。

精査して問題がなければ閲覧権限で公開したいと思います。

2021-07-26 04:37 UTC, wancom commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +しかし、Aizu Geek DojoのSAはみんな好奇心旺盛なので慣れてきたらきっと各々勉強してくれると願っています。
```suggestion
## あとがき
今回はGitとその周辺の基本的な部分しか触りしかしていません。Conflictの解決やRevertなど触れたいものは色々とありましたが、今回は時間の関係もあり省略しました。（でないと何時間もかかってしまいそう）  
しかし、Aizu Geek DojoのSAはみんな好奇心旺盛なので慣れてきたらきっと各々勉強してくれると願っています。

今回の勉強会で使用したスライドを公開しますので、もし興味がある方はぜひ覗いてみてください。
（理解しやすさを重視しているため正確でない表現があるかもしれませんがご了承ください。）
https://docs.google.com/presentation/d/1h5mLjagtjrIplXzoEXZIHbHZkKIa8vsbAHj-jZH4ka0/edit?usp=sharing
```

2021-07-26 04:40 UTC, wancom commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +しかし、Aizu Geek DojoのSAはみんな好奇心旺盛なので慣れてきたらきっと各々勉強してくれると願っています。
```suggestion
しかし、Aizu Geek DojoのSAはみんな好奇心旺盛なので慣れてきたらきっと各々勉強してくれると願っています。

今回の勉強会で使用したスライドを公開しますので、もし興味がある方はぜひ覗いてみてください。
（理解しやすさを重視しているため正確でない表現があるかもしれませんがご了承ください。）
https://docs.google.com/presentation/d/1h5mLjagtjrIplXzoEXZIHbHZkKIa8vsbAHj-jZH4ka0/edit?usp=sharing
```

2021-07-26 04:41 UTC, wancom commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +しかし、Aizu Geek DojoのSAはみんな好奇心旺盛なので慣れてきたらきっと各々勉強してくれると願っています。
スライドのURLを追加しました。

2021-07-26 04:42 UTC, wancom commented
@KATO-Eriko 改めてレビューをお願いします。

2021-07-28 00:04 UTC, KATO-Eriko requested changes

2021-07-28 00:04 UTC, KATO-Eriko commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +今回はGitとその周辺の基本的な部分しか触りしかしていません。Conflictの解決やRevertなど触れたいものは色々とありましたが、今回は時間の関係もあり省略しました。（でないと何時間もかかってしまいそう）
基本的な部分しか触りしかしていません -> 基本的な部分しか触れていません

2021-07-28 00:04 UTC, KATO-Eriko commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +しかし、Aizu Geek DojoのSAはみんな好奇心旺盛なので慣れてきたらきっと各々勉強してくれると願っています。
もし興味がある方はぜひ覗いてみてください。-> 興味がある方はぜひ覗いてみてください。
2点、修正したら、UPしてOKです！

2021-07-28 00:57 UTC, wancom commented on blog/2021-07-22-Git & GitHub勉強会を行いました.md
> +今回はGitとその周辺の基本的な部分しか触りしかしていません。Conflictの解決やRevertなど触れたいものは色々とありましたが、今回は時間の関係もあり省略しました。（でないと何時間もかかってしまいそう）
```suggestion
今回はGitとその周辺の基本的な部分しか触れていません。Conflictの解決やRevertなど触れたいものは色々とありましたが、今回は時間の関係もあり省略しました。（でないと何時間もかかってしまいそう）  
```

2021-07-28 01:03 UTC, wancom commented
@KATO-Eriko コメントありがとうございます。
思った以上に間違えていました。
以上修正しました。

2021-07-28 01:06 UTC, KATO-Eriko approved these changes
修正点確認しました。OKです、UPしてください！

2021-07-28 01:07 UTC, merged