[WIP] IoT Dojoの記事を追加
AizuGeekDojo/AizuGeekDojo.github.io pull request #104
Opened 2021-12-22 17:20 UTC by shinbunbun

## 関連するIssue番号

## 変更内容

IoT Dojoのブログ記事を追加
## 変更理由

## 関連するページ

/blog/2021-12-22/IoTDojo%20開催レポート
## スクリーンショット
![スクリーンショット 2021-12-23 2 19 36](https://user-images.githubusercontent.com/34409044/147130969-50fb9b88-53b4-4d6a-be2d-9fc0b340d415.png)

2021-12-22 17:47 UTC, suzakutakumi commented
120行ぐらい書いたので、最初に共同著者として書いてほしい(切実)

2021-12-22 17:51 UTC, shinbunbun commented
@suzakutakumi 
書きました！！！ありがとうありがとう..........

2021-12-22 17:53 UTC, suzakutakumi commented
ありがとう!
あと文章とかは拙いので、どんどん修正してかまわないです

2021-12-22 17:53 UTC, shinbunbun commented
@KATO-Eriko 
レビューお願いします🙏
https://deploy-preview-104--vigorous-saha-ca883f.netlify.app/blog/2021-12-22/IoTDojo%20%E9%96%8B%E5%82%AC%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88

2021-12-24 06:01 UTC, KATO-Eriko commented
日本語の修正とコメントを付けました。

2021-12-24 06:02 UTC, KATO-Eriko commented
ごめん、なんか間違えてcloseしちゃった。上の修正反映お願いします！

2021-12-24 06:03 UTC, wancom commented
多分コメントも付けられていないようなのでもう一度してもらえますか？

2021-12-24 06:07 UTC, KATO-Eriko commented
@wancom file changedの+をクリックしてコメント書いたんだけど、見えていないのかな？

2021-12-24 06:08 UTC, KATO-Eriko requested changes, later dismissed
これか！コメントつけました！

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +今回はGeek Dojoで開催した「IoT Dojo」というイベントについて紹介したいと思います。
```suggestion
今回はAizuGeek Dojoで開催した「IoT Dojo」というイベントについて報告します。
```

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +初心者対象ということもあり、シールドに刺すだけで簡単にモジュールが使えるFaboを採用しました。Faboのモジュールは[株式会社FaBo](https://fabo.store/)様にお貸し頂ました。
FaBoを採用しました。
FaBoのモジュールは[株式会社FaBo](https://fabo.store/)様にお借りしました。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +勉強会前日にGeek SA陣が必死で半田付けをしてなんとか完成しました。
製作中にピンソケットをいくつか破壊してしまい、数が足りなくなるというトラブルがあったり、XXXなことがあったりしましたが、勉強会前日にGeek SA陣が必死で半田付けをしてなんとか参加人数分のシールドを完成させました。（SAのがんばりと苦労をもう少し書けるといいな）

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +
```suggestion
1，2年生を中心に22名の参加がありました！

```

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ハッカソンは6チームに分かれて行い、1チーム1人SAがアシスタントについてサポートを行いました。
1チームに1人SAがアシスタントとしてサポートを行いました。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ここからは、しんぶんぶんが成果物発表にこれなかったため、IoTDojoで講師を務めた朱雀 匠が代わりに書きます。
ここはハンドルネームでいい？冒頭は高棟で本名なので、だれがしんぶんぶんか見ている人はわかりません。統一した方がいいかな。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +コマンドの結果、発表順は`3,1,2,4,6,5`でしたが、Type-CとHDMIの変換が無かったため以下のようになりました。
この文章はなくてもいいかな？

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +- 光を止めるには、ブラウザ上で行われるOXゲームに勝たないといけない
光を消すには、

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +この作品は、家の温度と照度の1日のデータをネット上で公開する物です。
公開するものです。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +自分の生活を公開することで、友達などに生活を監視してもらい、生活習慣を正すとのことです。
生活習慣を正したい、という思いで開発したとのこと。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +この作品は、家の温度と照度の1日のデータをネット上で公開する物です。
照度か光度か、以下統一してください。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +このチームは、技術力が高く、正直自分も何をやっているのかわからない事がありました。
わからない部分が

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +
122~125を以下のようにしてはどうでしょう。
Common Lispでサーバを書くという高度なことをやっていました。（取り入れていました？サーバを書く、という日本語あっている？）
しかし、発表では技術についての説明が多く、初学者(多くの受講者)は理解がしにくかったかもしれません。
開発しようと思った目的や作ったものについての説明がもっとあるとよかったです。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +この作品は、会津大学学祭室で手動で知らせている開閉状況を自動化で知らせる物です。
129ﾄ130をまとめて、以下でどうでしょうか。
チーム４が作成したものは、会津大学学祭室の扉の開閉について、自動でお知らせするSlackBotです。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ボタンを押したときに、閉めた時は、年月日・曜日・日時・活動時間を通知します。
140と141について、以下のようなものだったと思うのですが、合ってますか？ブレーカーを上げて開けた、ボタンを押して閉めた、だけだと、扉が物理的に閉まっているのか不明な文章になっているかと。。。
ブレーカーにレシーバー（？）を付けて、入室したときにブレーカーを上げることで「開けた」と通知、退室する際には扉に取り付けた（？）ESP32と接続したボタンを押しから退室することで、「閉めた」と通知をするものです。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +一時的に部屋を出る時に鍵を持ち出した・戻ってきたを知らせるための定型文です。
147と148について、どんな定型文を送っているのかを記述しないと、上の画像もあいまって混乱します。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +今後は、Bluetoothやセンサを使用して全自動化を図るそうです。
158~162は感想に含めていいかな。失敗について、と書かれるとチーム４の人は悲しくなっちゃうかも。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム4の作品は、単純ではありますが、便利だったりネタ要素が含まれていたりして面白い作品でした。
閉めの判定の全自動化したかったけれど、うまくいかず、半自動に諦めたらしいです。今後もBluetoothやセンサを使用して全自動化を図りたいと意気込みを語ってくれました。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム1は、LINEを使って家のエアコンをESP32で操作させました。
EPS32とLINEBotを使って家のエアコンを遠隔操作するものでした。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ただ、発表の中でソースコード全てをべた張りして説明している部分があり、理解がしにくかったです。(文字が小さすぎて読めなーい)
ただ、発表ではソースコード全てをベタ張りして説明していたので理解がしにくかったです。(文字が小さすぎて読めなーい)

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +作成理由としては、発表日12/22の2日後にクリスマスがあるからです。
発表日である12/22の2日後に

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +アプリの作成には、MITのApp Inventorを使用しています。
アプリの作成には、MITが提供している（公開している？）App Inventorを使用しています。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +デモでは、実際にスマホからの操作で、LEDを光らせたり走行させたりしていました。
ツリーを走行させたりしていました。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム6の作品は、Faboを使わない&レーザーカッターで機体を作るという、ハードウェアが強い作品でした。
FaBoを使わない&レーザーカッターと3Dプリンタで機体を作るという、

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム5は、ブラウザから家のエアコンをESP32で操作させました。
EPS32で操作させるものでした。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +上記のように話してはいますが、このチームの作品は残念ながら完成していません。
しかし、残念ながらこのチームの作品は完成できませんでした。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +発表時に出来たものは、webからesp32に起動の情報を送る機能のみで、エアコンを起動する機能を完成出来なかったようです。
webからESP32に起動の情報を送る機能のみで、ESP32からエアコンを起動する機能を完成できなかったようです。（あってるかな？）

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +
237~239は1行ずつ改行した方がいいです。

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +## IoT Dojoを開催した感想
IoT Dojoを主催した感想

2021-12-24 06:08 UTC, KATO-Eriko commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +また、改めてESP32の勉強が出来たり、新しい可能性が知れて自分の身にもなりました。
以下に、ぶんぶんの感想も記入してほしいです！イベントの説明で出てきたっきりなのはさみしい。
アシスタントとしてチーム開発をした感想や、参加者の様子（夜中までプログラム組んだけど動かないなどの苦労話とか）もあるといいな。

2021-12-24 06:11 UTC, wancom commented
修正しやすいようにコメントを修正するのでしばらくお待ちください…

2021-12-24 06:13 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +初心者対象ということもあり、シールドに刺すだけで簡単にモジュールが使えるFaboを採用しました。Faboのモジュールは[株式会社FaBo](https://fabo.store/)様にお貸し頂ました。
```suggestion
初心者対象ということもあり、シールドに刺すだけで簡単にモジュールが使えるFaboを採用しました。Faboのモジュールは[株式会社FaBo](https://fabo.store/)様にお借りしました。
```

2021-12-24 06:14 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ハッカソンは6チームに分かれて行い、1チーム1人SAがアシスタントについてサポートを行いました。
```suggestion
ハッカソンは6チームに分かれて行い、1チームに1人SAがアシスタントとしてサポートを行いました。
```

2021-12-24 06:14 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +- 光を止めるには、ブラウザ上で行われるOXゲームに勝たないといけない
```suggestion
- 光を消すには、ブラウザ上で行われるOXゲームに勝たないといけない
```

2021-12-24 06:15 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +この作品は、家の温度と照度の1日のデータをネット上で公開する物です。
```suggestion
この作品は、家の温度と照度の1日のデータをネット上で公開するものです。  
```

2021-12-24 06:15 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +自分の生活を公開することで、友達などに生活を監視してもらい、生活習慣を正すとのことです。
```suggestion
自分の生活を公開することで、友達などに生活を監視してもらい、生活習慣を正したい、という思いで開発したとのことです。
```

2021-12-24 06:16 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +このチームは、技術力が高く、正直自分も何をやっているのかわからない事がありました。
```suggestion
このチームは、技術力が高く、正直自分も何をやっているのかわからない部分がありました。  
```

2021-12-24 06:17 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +発表の改善点はいっぱいありましたが、技術的にもモノ的にも面白い作品でした。
```suggestion
Common Lispでサーバを書くという高度なことをやっていました。
しかし、発表では技術についての説明が多く、初学者(多くの受講者)は理解がしにくかったかもしれません。
開発しようと思った目的や作ったものについての説明がもっとあるとよかったです。
```

2021-12-24 06:19 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +この作品は、会津大学学祭室で手動で知らせている開閉状況を自動化で知らせる物です。
```suggestion
チーム４が作成したものは、会津大学学祭室の扉の開閉について、**自動で**お知らせするSlackBotです。
```

2021-12-24 06:21 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム1は、LINEを使って家のエアコンをESP32で操作させました。
```suggestion
チーム1は、EPS32とLINEBotを使って家のエアコンを遠隔操作するものでした。
```

2021-12-24 06:21 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ただ、発表の中でソースコード全てをべた張りして説明している部分があり、理解がしにくかったです。(文字が小さすぎて読めなーい)
```suggestion
ただ、発表ではソースコード全てをベタ張りして説明していたので理解がしにくかったです。(文字が小さすぎて読めなーい) 
```

2021-12-24 06:21 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +作成理由としては、発表日12/22の2日後にクリスマスがあるからです。
```suggestion
作成理由としては、発表日である12/22の2日後にクリスマスがあるからです。
```

2021-12-24 06:23 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +アプリの作成には、MITのApp Inventorを使用しています。
```suggestion
アプリの作成には、MITが公開しているApp Inventorを使用しています。 
```

2021-12-24 06:23 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +デモでは、実際にスマホからの操作で、LEDを光らせたり走行させたりしていました。
```suggestion
デモでは、実際にスマホからの操作で、LEDを光らせたりツリーを走行させたりしていました。
```

2021-12-24 06:23 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム6の作品は、Faboを使わない&レーザーカッターで機体を作るという、ハードウェアが強い作品でした。
```suggestion
チーム6の作品は、FaBoを使わない&レーザーカッターと3Dプリンタで機体を作るという、ハードウェアが強い作品でした。  
```

2021-12-24 06:24 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +チーム5は、ブラウザから家のエアコンをESP32で操作させました。
```suggestion
チーム5は、ブラウザから家のエアコンをEPS32で操作させるものでした。
```

2021-12-24 06:24 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +上記のように話してはいますが、このチームの作品は残念ながら完成していません。
```suggestion
しかし、残念ながらこのチームの作品は完成できませんでした。
```

2021-12-24 06:25 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +発表時に出来たものは、webからesp32に起動の情報を送る機能のみで、エアコンを起動する機能を完成出来なかったようです。
```suggestion
発表時に出来たものは、webからESP32に起動の情報を送る機能のみで、ESP32からエアコンを起動する機能を完成できなかったようです。
```

2021-12-24 06:25 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +3位: チーム2
```suggestion
1位: チーム1,チーム6  
2位: チーム3  
3位: チーム2  
```

2021-12-24 06:26 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +## IoT Dojoを開催した感想
```suggestion
## IoT Dojoを主催した感想
```

2021-12-24 06:27 UTC, wancom commented
修正できる範囲で修正してみました。
修正箇所が多いのでSuggestionを使う場合はbatchに入れてcommitしてください。

2021-12-25 05:13 UTC, suzakutakumi commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +ここからは、しんぶんぶんが成果物発表にこれなかったため、IoTDojoで講師を務めた朱雀 匠が代わりに書きます。
高棟(しんぶんぶん)と記述しておきます

2021-12-25 05:16 UTC, suzakutakumi commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +コマンドの結果、発表順は`3,1,2,4,6,5`でしたが、Type-CとHDMIの変換が無かったため以下のようになりました。
一応、順番が決まった経緯なのでほしいかと思いました。

2021-12-25 07:14 UTC, suzakutakumi commented
@wancom 
ぶんぶんの感想以外を修正しました!

2021-12-27 01:00 UTC, shinbunbun commented
@wancom @KATO-Eriko 感想追加しましたー

2021-12-28 02:37 UTC, wancom reviewed
全体的に意図した改行を入れられていない可能性があるのでもう一度確認をお願いします。
みた感じ、問題はなさそうです。
いくつかレイアウトが崩れていた箇所があったので追加しました。
今更ですが、記事が長いので準備、勉強会編と発表会編の2つに分割してもよかったかもしれません。

@KATO-Eriko 修正が多岐にわたって発生したので、お手数ですが全ての修正が終わったら再度レビューをお願いします。
@shinbunbun 一応修正の提案を含むのでCommentとしてつけますが、@KATO-Eriko のレビューが通ったらマージしてOKです。

2021-12-28 02:37 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +コマンドの結果、発表順は`3,1,2,4,6,5`でしたが、Type-CとHDMIの変換が無かったため以下のようになりました。
ここら辺、何か粋な説明があるといいかもしれませんね。

```
発表順については会津大学生らしく以下のコマンドを使って決めました。 
```

2021-12-28 02:37 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +<img width="1440" alt="スクリーンショット 2021-12-23 9 33 41" src="https://user-images.githubusercontent.com/71514776/147170595-5d1c2fc6-e506-40c3-84a4-06e54252b011.png">
サニタイズの影響か、きちんと表示されていなかったのでMD記法にしてください。

```suggestion
![スクリーンショット 2021-12-23 9 33 41](https://user-images.githubusercontent.com/71514776/147170595-5d1c2fc6-e506-40c3-84a4-06e54252b011.png)
```

2021-12-28 02:37 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +発表の改善点はいっぱいありましたが、技術的にもモノ的にも面白い作品でした。
少しだけ。
```suggestion
このチームは、技術力が高く、正直自分も何をやっているのかわからない部分がありました。  
Common Lispでサーバを書くという高度なことをやっていました。しかし、発表では技術についての説明が多く、初学者(多くの受講者)は理解がしにくかったかもしれません。開発しようと思った目的や作ったものについての説明がもっとあるとよかったです。   
発表の改善点はいっぱいありましたが、技術的にもモノ的にも面白い作品でした。
```

2021-12-28 02:37 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +目的としては、日常生活で役立つものを作りたいというものがあり、会津の厳しい冬を超えるために作成したそうです。
```suggestion
チーム1は、EPS32とLINEBotを使って家のエアコンを遠隔操作するものでした。  
この作品は、LINEBotを介してスマホとESP32を繋げ、スマホで家の温度情報を見たり、エアコンを起動させたりできます。  
目的としては、日常生活で役立つものを作りたいというものがあり、会津の厳しい冬を超えるために作成したそうです。
```

2021-12-28 02:37 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +この作品は、サーバを介してスマホとESP32を繋げ、エアコンを起動させます。
```suggestion
チーム5は、ブラウザから家のエアコンをEPS32で操作させるものでした。  
この作品は、サーバを介してスマホとESP32を繋げ、エアコンを起動させます。  
```

2021-12-28 02:37 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +**
ここは強調表示だったかな？

```suggestion
**1位: チーム1,チーム6  
2位: チーム3  
3位: チーム2**
```

2021-12-29 05:48 UTC, suzakutakumi reviewed
このような感じでどうでしょうか?

2021-12-29 05:48 UTC, suzakutakumi commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +発表順を以下のコマンドで決めました。
```suggestion
発表順については会津大学生らしく以下のコマンドを使って決めました。  
```

2021-12-29 07:24 UTC, wancom commented on blog/2021-12-22-IoTDojo 開催レポート.md
> +発表順を以下のコマンドで決めました。
いいと思います！

2021-12-29 22:40 UTC, wancom approved these changes
@KATO-Eriko の代わりにApproveします

2021-12-29 22:56 UTC, merged