Feature/#87 add docker
AizuGeekDojo/AizuGeekDojo.github.io pull request #88
Opened 2021-05-12 02:50 UTC by shinbunbun

## 関連するIssue番号
close #87 

## 変更内容
Dockerの設定ファイルを追加

## 変更理由

## 関連するページ

## スクリーンショット

2021-05-12 03:46 UTC, wancom requested changes
https://crieit.net/posts/docker-build-volume
https://qiita.com/shindex/items/1deb070222d55a7d645d
多分こんな感じでmount前にbuildされるだろうからうまく動かない可能性もあるかも。

DockerfileのSuggestionのような感じであれば間違いなくうまくいくのかなという気がする。
これでもパッケージが更新されたらコンテナーをビルドし直すか、コンテナーに入ってからyarn installが必要。

もしくはシーケンスを確認する必要があるけど、CMDを使うのもありかも。
これならマウント後に実行される。

最後に一応`.dockerignore`で`node_modules`を除外しておいた方がいいかも。

2021-05-12 03:46 UTC, wancom commented on Dockerfile
> +RUN yarn install
```suggestion
WORKDIR /code

COPY package.json .
RUN yarn install
```

2021-05-12 07:48 UTC, wancom commented
> 最後に一応`.dockerignore`で`node_modules`を除外しておいた方がいいかも。

dockerignoreも欲しいな…

2021-05-12 12:57 UTC, shinbunbun commented
@wancom 追加しましたー

2021-05-12 21:54 UTC, wancom approved these changes
LGTMです

2021-05-13 00:24 UTC, shinbunbun commented
@wancom 真鯵しちゃって大丈夫ですか？

2021-05-13 00:28 UTC, wancom commented
してください！

2021-05-13 00:29 UTC, merged